version: "3.7"

services:
  sim_anuencia:
    image: perrout/sim_anuencia:v162
    ports:
      - "3001:3001"
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - webnet

  mongodb:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongodb:/data/db
    networks:
      - webnet

networks:
  webnet:
